- name: Create instance
  ec2_instance:
    image_id: "{{ ec2_ami }}"
    instance_type: "{{ ec2_instance_type }}"
    vpc_subnet_id: "{{ ec2_private_subnets|first }}"
    network:
      assign_public_ip: no
    security_groups: "{{ ec2_groups }}"
    key_name: "{{ ec2_keypair }}"
    tags:
      Name: "{{ ec2_base_name|replace('-', ' ')|title }} Deployment"
    wait: yes
    region: "{{ aws_region }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  register: ec2

- name: Wait for SSH
  wait_for:
    host: "{{ ec2.instances[0].private_ip_address }}"
    port: 22

- name: Add instance to Ansible groups
  add_host:
    groups: "{{ ansible_groups }}"
    name: "{{ ec2.instances[0].private_ip_address }}"
