- name: Create instance
  ec2:
    image: "{{ ec2_ami }}"
    instance_type: "{{ ec2_instance_type }}"
    vpc_subnet_id: "{{ ec2_private_subnets[0] }}"
    assign_public_ip: no
    group_id: "{{ ec2_groups }}"
    keypair: "{{ ec2_keypair }}"
    instance_tags:
      Name: "{{ ec2_base_name|replace('-', ' ')|title }} Deployment"
    wait: yes
    region: "{{ aws_region }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  register: ec2

- name: Wait for SSH
  wait_for:
    host: "{{ ec2.instances[0].private_ip }}"
    port: 22

- name: Install Python
  raw: apt update && apt install python -y
  delegate_to: "ubuntu@{{ ec2.instances[0].private_ip }}"
  become: yes
  retries: 5
  delay: 10
  register: result
  until: result is succeeded

- name: Add instance to Ansible groups
  add_host:
    groups: "{{ ansible_groups }}"
    name: "{{ ec2.instances[0].private_ip }}"
